module Utils
  SINGLE_LICENSE_PRICE = 99
  UNLIMITED_LICENSE_PRICE = 299

  JUMPSTART_VERSION = "1.1"
  RAILS_VERSION = "6.0"
  RUBY_VERSION = "2.6.1"
  STRIPE_VERSION = "2.3"
  BRAINTREE_VERSION = "2.3"
end